[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/tcpproxy"
